version: '3.4'

networks:
  mynetwork:
    name: mynetwork
    attachable: true

services:

  f5_oidc:
    container_name: f5_oidc
    build:
      context: ./
      dockerfile: ./docker/nginxplus-25-ubuntu18.04/Dockerfile
    image: f5_oidc
    ports:
      - 443:443
    volumes:
      - ./common/backend:/etc/nginx/backend
      - ./common/oidc:/etc/nginx/oidc
      - ./common/template:/etc/nginx/template
      - ./common/frontend:/usr/share/nginx/html/
    networks:
      - mynetwork

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 8443:8443
    volumes:
      - ./common/certs/oidc_simulator_temp.crt:/etc/x509/https/tls.crt
      - ./common/certs/oidc_simulator_temp.key:/etc/x509/https/tls.key
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: host.docker.internal
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
    command:
      start-dev
    networks:
      - mynetwork
